version: "3"

services:
  mysql:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    networks:
      - app

  php8:
    build:
      context: ./build/php8
    restart: always
    volumes:
      - ./web:/web
      - ./conf/php8/fpm:/usr/local/etc/php-fpm.d
      - ./conf/php8/php/php.ini:/usr/local/etc/php/php.ini
      - ./log/php8:/var/lib/log
    ports:
      - "2345:2345"
    cap_add:
      - SYS_PTRACE
    networks:
      - app

  nginx:
    image: nginx:1.21.0-alpine
    restart: always
    volumes:
      - ./web:/web
      - ./log/nginx/error/error.log:/var/log/nginx/error.log
      - ./log/nginx/access/access.log:/var/log/nginx/access.log
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app

  redis:
    image: redis:6.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app

  memcached:
    image: memcached:1.6.9
    restart: always
    networks:
      - app

  rabbitmq:
    image: rabbitmq:3.8.17-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app
volumes:
  mysql:

networks:
  app:
    name: my-app-network
    ipam:
      config:
        - subnet: 172.28.0.0/16


